version: '3.8'

services:
  backend:
    build:
      context: ../apps/backend/Products
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./nginx-web-server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NGINX_PORT=8080
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3333:3333"
    depends_on:
      - frontend

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Products
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ../apps/backend/Products/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - database-volume:/var/lib/mysql

volumes:
  database-volume:
    driver: local

networks:
  host:
    name: host
    external: true